### ISSUE TITLE
 No rio_stac generated items found error

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-generator#31]
```
2023-07-03 16:54:43.413 | INFO     | app.core.redis:redis_listener:35 - Received item from Redis: (b'os_eo_post_cog_conversion_validator_success_output', b'{"metadata": {"TileName": "SX8988", "FileName": "129266-00000000-0000-0000-0000-000000149115.tiff", "FlightDate": "2016-07-19T00:00:00", "Submitted": "2018-03-15T16:42:34.3028593+00:00", "Version": 129266}, "metadata_url": "https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json", "discovered_files": ["https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json", "https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.tiff"], "parser": "os_heightstore_dsm1m", "files_converted_to_cog": [], "files": ["https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json"], "gdal_infos": []}')
Exception in thread Thread-1 (redis_listener):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/./app/core/redis.py", line 38, in redis_listener
    stac = STACItemCreator(item_dict).create_item()
  File "/app/./app/stac/services/stac_item_creator.py", line 61, in create_item
    self._add_tiff_stac_metadata()
  File "/app/./app/stac/services/stac_item_creator.py", line 127, in _add_tiff_stac_metadata
    raise ValueError("No rio_stac generated items found.")
ValueError: No rio_stac generated items found.

```

**Comment by james-hinton** [comment]
At least one accessible TIFF/TIF must be supplied in the payload

**Comment by ivica3730k** [comment]
The validator didn't catch that for some reason @mountaincharlie 

Could it be that the file is there but it is corrupt?

**Comment by ivica3730k** [comment]
sx8992 keeps on failing @mountaincharlie, so that is okay as post-cog validator is still in the making for os_heightstore_dsm1m parser

![image](https://github.com/SpatialDays/stac-generator/assets/17437897/b371e29b-61e5-4d41-a46b-30e456351a2c)
