### ISSUE TITLE
redis listener stays crashed on exception

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-generator#32]
Redis listener stays crashed on exception as it runs in a thread alongside the main stac-fast API application.
```
2023-07-03 16:54:43.413 | INFO     | app.core.redis:redis_listener:35 - Received item from Redis: (b'os_eo_post_cog_conversion_validator_success_output', b'{"metadata": {"TileName": "SX8988", "FileName": "129266-00000000-0000-0000-0000-000000149115.tiff", "FlightDate": "2016-07-19T00:00:00", "Submitted": "2018-03-15T16:42:34.3028593+00:00", "Version": 129266}, "metadata_url": "https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json", "discovered_files": ["https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json", "https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.tiff"], "parser": "os_heightstore_dsm1m", "files_converted_to_cog": [], "files": ["https://oseoinfrastagingstrgacc.blob.core.windows.net/heightstore-dsm1m-raw/data/incremental/2021/01/22/16/129266-00000000-0000-0000-0000-000000149115.json"], "gdal_infos": []}')
Exception in thread Thread-1 (redis_listener):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/./app/core/redis.py", line 38, in redis_listener
    stac = STACItemCreator(item_dict).create_item()
  File "/app/./app/stac/services/stac_item_creator.py", line 61, in create_item
    self._add_tiff_stac_metadata()
  File "/app/./app/stac/services/stac_item_creator.py", line 127, in _add_tiff_stac_metadata
    raise ValueError("No rio_stac generated items found.")
ValueError: No rio_stac generated items found.
```

Either:
- separate the two in multiple start commands
- make a HTTP health probe for redis part
- exit the whole code if one of the threads dies

**Comment by james-hinton** [comment]
Why not just reintroduce the `except` block and make a redis push to an errors channel? Seems mad that we now have to stop the entire application and manually start it up again every time there's an error?

**Comment by ivica3730k** [comment]
That is how it should work with Kubernetes tho, so you have error logs and then you know something is wrong

Edit: it is not a manual restart, the Kubernetes does it

**Comment by ivica3730k** [comment]
> Why not just reintroduce the `except` block and make a redis push to an errors channel? Seems mad that we now have to stop the entire application and manually start it up again every time there's an error?

do we have an error channel for this?

**Comment by ivica3730k** [comment]
> Why not just reintroduce the `except` block and make a redis push to an errors channel? Seems mad that we now have to stop the entire application and manually start it up again every time there's an error?

if we are to do that, can we change the thread not to run in deamon mode, so when for any reason redis crashes the HTTP listener will stop too, as we need kubernetes to replace the pod as soon redis or HTTP is down.

This would be the reason I would go for 2 separate entrypoints, like this. As it is easier for K8S to determine when the pod is dead:

![image](https://github.com/SpatialDays/stac-generator/assets/17437897/161abb59-2d65-4729-b1c6-97e84bfa8500)

**Comment by ivica3730k** [comment]
this is what i propose: https://github.com/SpatialDays/stac-generator/pull/33
